### ISSUE TITLE
Hi buddy,mind if I pick your brains for a minute?

### ISSUE THREAD

**Issue by YANKT** [aub-mind/Robust-Seizure-Prediction#1]
I have a few questions:
1.In ‘sampling_CHBMIT.csv’,Subject,Electrode,Ictal,Interictal,ictal_ovl,interictal_unspl，‘interictal_unspl’what does that mean?and subject 13-23 Ictal and Interictal value why none? other subject Ictal and Interictal value how is it calculated?
2.'special_interictal.csv' What does it do？special interictal I don't quite understand
3.In 'segmentation.csv',0,1, -1,3  What does it stand for?
THX.

**Comment by Morilla123** [comment]
I have some questions:
1.In ‘sampling_CHBMIT.csv’,Subject,Electrode,Ictal,Interictal,ictal_ovl,interictal_unspl，‘interictal_unspl’, what does that mean?

(subject, channels according to the 20-10 system, seizure period, period between seizure and seizure, ictal_ovl I think is the capture of the seizure period only (but I really don't know), and unspl refers to being unsampling). I know that my answers are not very helpful but it is what occurs to me, at this moment I would like to see the context.

and subject 13-23 Ictal and interictal value, why none?

This dataset, based on what I read about the reviews in the review "Machine Learning for Predicting Epileptic Seizures Using EEG Signals: A Review" where you name the different datasets, it says that the CHB-MIT dataset, although it is one of the most complete, it has errors in data acquisition and missing data. This must be one of the cases.

 other subject Ictal and interictal value, how is it calculated?
From the bibliography I did not find a clear definition, but there is reference to the metrics of the signal during those periods. From what I understand there is no single way to calculate or describe it.

2.'special_interictal.csv' What does it do? special interictal i don't understand very well

I don't know where that csv is, could you tell me.

3.In 'segmentation.csv',0,1, -1,3, what does it mean?

Like the previous point, I don't know where that achievement is.

You would like to coordinate a video call for next week and we discuss some doubts together. I tell you that this project was started and abandoned a while ago. In a few weeks it will reopen, your contribution in the area would be of great help, and maybe we can help you, we are two biomedical engineering students specialized in deep learning.
